"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

import os
import logging
from pathlib import Path
from urllib.parse import urlparse
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment file if present
load_dotenv(BASE_DIR / '.env')

# Security
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

if not SECRET_KEY and not DEBUG:
    raise ImproperlyConfigured(
        'SECRET_KEY must be set in production via environment variables.'
    )

SECRET_KEY = SECRET_KEY or 'django-insecure-0!a_t=sahftj+3ge2d%j8d$z1l7+7u-c$ht=pja08++u72c-h2'

DEFAULT_ALLOWED_HOSTS = 'localhost,127.0.0.1,.vercel.app,.localhost'
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('ALLOWED_HOSTS', DEFAULT_ALLOWED_HOSTS).split(',') if host.strip()
]
vercel_host = (os.environ.get('VERCEL_URL') or '').strip()
if vercel_host:
    ALLOWED_HOSTS.append(vercel_host)
if DEBUG:
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + ['localhost', '127.0.0.1', '[::1]', '.localhost', 'testserver']))

DEFAULT_CSRF_TRUSTED_ORIGINS = 'http://localhost:8000,http://127.0.0.1:8000,https://localhost:8000'
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', DEFAULT_CSRF_TRUSTED_ORIGINS).split(',') if origin.strip()
]
if vercel_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{vercel_host}')
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(['http://localhost:8000', 'http://127.0.0.1:8000'])

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
logger = logging.getLogger(__name__)

# ----------------------------------------------------
# Installed Applications
# ----------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'cloudinary_storage',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'cloudinary',

    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'accounts',
    'posts',
    'commentsapp',
    'adminpanel',
    'notifications',
]

SITE_ID = 1
cloudinary_cloud_name = (os.environ.get('CLOUDINARY_CLOUD_NAME') or '').strip()
cloudinary_api_key = (os.environ.get('CLOUDINARY_API_KEY') or '').strip()
cloudinary_api_secret = (os.environ.get('CLOUDINARY_API_SECRET') or '').strip()
cloudinary_placeholders = {'your_cloud_name', 'your_api_key', 'your_api_secret', 'demo'}
cloudinary_configured = all(
    value and value.lower() not in cloudinary_placeholders
    for value in (cloudinary_cloud_name, cloudinary_api_key, cloudinary_api_secret)
)

if cloudinary_configured:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': cloudinary_cloud_name,
        'API_KEY': cloudinary_api_key,
        'API_SECRET': cloudinary_api_secret,
    }
    STORAGES = {
        'default': {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    CLOUDINARY_STORAGE = {'CLOUD_NAME': '', 'API_KEY': '', 'API_SECRET': ''}
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
# ----------------------------------------------------
# Middleware
# ----------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
# ----------------------------------------------------
# URL Configuration
# ----------------------------------------------------

ROOT_URLCONF = 'config.urls'

# ----------------------------------------------------
# Templates
# ----------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ----------------------------------------------------
# Database
# ----------------------------------------------------

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    parsed = urlparse(DATABASE_URL)
    if parsed.scheme not in ('postgres', 'postgresql'):
        raise ImproperlyConfigured('DATABASE_URL must start with postgres:// or postgresql://')

    database_config = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    database_config['OPTIONS'] = {'sslmode': 'require'}
    DATABASES = {"default": database_config}
else:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DATABASE_URL must be set in production environment.'
        )

    logger.warning(
        'DATABASE_URL not configured; using local SQLite fallback for development.'
    )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ----------------------------------------------------
# Allauth Settings
# ----------------------------------------------------

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

if os.environ.get('RESEND_API_KEY'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.resend.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'resend'
    EMAIL_HOST_PASSWORD = os.environ.get('RESEND_API_KEY')
    DEFAULT_FROM_EMAIL = 'Whisperbook <onboarding@resend.dev>'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Whisperbook <noreply@example.com>'

# Use default allauth adapters so existing users can log in and Google auth remains enabled.
# ----------------------------------------------------
# Custom User Model
# ----------------------------------------------------

AUTH_USER_MODEL = 'accounts.User'

# ----------------------------------------------------
# Authentication Backends
# ----------------------------------------------------

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# ----------------------------------------------------
# Password Validation
# ----------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------------------------------
# Internationalization
# ----------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ----------------------------------------------------
# Static Files
# ----------------------------------------------------

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ----------------------------------------------------
# Media Files
# ----------------------------------------------------

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------------------
# Default Primary Key
# ----------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'